"""adding optimizer and layers params to schema

Revision ID: 0cc164b47660
Revises: 1b449191b314
Create Date: 2020-01-09 12:20:30.473372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc164b47660'
down_revision = '1b449191b314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algos', sa.Column('layers', sa.Integer(), nullable=True))
    op.add_column('algos', sa.Column('optimizer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algos', 'optimizer')
    op.drop_column('algos', 'layers')
    # ### end Alembic commands ###
