"""adding some cols for model accuracy

Revision ID: e7e5fec73cc1
Revises: 0cc164b47660
Create Date: 2020-01-10 15:41:55.429495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e5fec73cc1'
down_revision = '0cc164b47660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algos', sa.Column('num_correct', sa.Integer(), nullable=True))
    op.add_column('algos', sa.Column('num_pred', sa.Integer(), nullable=True))
    op.add_column('algos', sa.Column('val_acc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algos', 'val_acc')
    op.drop_column('algos', 'num_pred')
    op.drop_column('algos', 'num_correct')
    # ### end Alembic commands ###
